background            #0a0f1c
foreground            #eaf3ff

# black
color0  #0a0f1c
color8  #2a3550

# red
color1  #e23b3b
color9  #ff5a6a

# green
color2  #8ab84a
color10 #a6d066

# yellow
color3  #e0b052
color11 #ffcf6b

# blue
color4  #1ea7ff
color12 #5fc4ff

# magenta
color5  #6f7fc8
color13 #8f9fe0

#cyan
color6  #19c4d8
color14 #5fe0ee

#white
color7  #eaf3ff
color15 #eaf3ff

# Transparency
background_opacity 0.8